services:
  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # The env file should set POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
        read_only: true
      - db-data:/var/lib/postgresql/data
    networks:
      - psycho-backend-network

  back:
    image: kadolphe/psycho-back-tests:bcd6cb0
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - type: bind
        source: .env
        target: /usr/src/app/.env
        read_only: true
    networks:
      - psycho-backend-network
    ports:
      - "8000:8000"

volumes:
  db-data:
    driver: local

networks:
  psycho-backend-network:
    driver: bridge

