services:
  db:
    image: postgres:18
    container_name: psycho-db
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # The env file should set POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./postgres-init
        target: /docker-entrypoint-initdb.d
        read_only: true
      - db-data:/var/lib/postgresql
    networks:
      - psycho-db-network
    # For admin tasks outside the container
    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 0s

  redis:
    image: redis:8.2
    container_name: psycho-redis
    restart: always
    networks:
      - psycho-back-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  # We will be using two instances of the backend for load balancing.
  back-1:
    image: kadolphe/psycho-back-tests:latest
    container_name: psycho-back-1
    user: root
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - psycho-back-network
      - psycho-db-network
    healthcheck:
      test: python -c 'import urllib.request; urllib.request.urlopen("http://localhost:8000")' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - static:/staticfiles
      - media:/mediafiles
      - /var/run/docker.sock:/var/run/docker.sock # this is necessary to launch docker cmds inside the container to run on the host (eg. update_services.sh)
      - /usr/bin/docker:/usr/bin/docker         # Docker CLI
      - /usr/local/lib/docker/cli-plugins:/usr/lib/docker/cli-plugins # compose plugin
      - ./scripts:/usr/src/app/scripts
      - ./configs:/etc/back
  back-2:
      image: kadolphe/psycho-back-tests:latest
      container_name: psycho-back-2
      user: root
      restart: always
      depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy
        back-1:
          condition: service_healthy # back-1 and back-2 should not start simultaneously (only one should initialize the DB)
      env_file:
        - .env
      networks:
        - psycho-back-network
        - psycho-db-network
      healthcheck:
        test: python -c 'import urllib.request; urllib.request.urlopen("http://localhost:8000")' || exit 1
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
      volumes:
        - static:/staticfiles
        - media:/mediafiles
        - /var/run/docker.sock:/var/run/docker.sock # this is necessary to launch docker cmds inside the container to run on the host (eg. update_services.sh)
        - /usr/bin/docker:/usr/bin/docker         # Docker CLI
        - /usr/local/lib/docker/cli-plugins:/usr/lib/docker/cli-plugins # compose plugin
        - ./scripts:/scripts
        - ./configs:/etc/back
  front:
    image: kadolphe/psycho-front-tests:latest
    container_name: psycho-front
    restart: always
    env_file:
        - .env.front
    depends_on:
      back-1:
        condition: service_healthy
      back-2:
        condition: service_healthy
    networks:
      - psycho-front-network
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # reverse proxy and load balancing
  nginx:
    image: nginx:1.29
    container_name: psycho-nginx
    env_file:
        - .env.front
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - static:/staticfiles:ro
      - media:/mediafiles:ro
    depends_on:
      back-1:
        condition: service_healthy
      back-2:
        condition: service_healthy
      front:
        condition: service_healthy
    networks:
      - psycho-back-network
      - psycho-front-network
    ports:
      - "81:80"

# --------------------------------------------
# Backup services : runs manually
# Usage : docker compose run --rm db-backup
#        docker compose run --rm media-backup
# --------------------------------------------

  db-backup:
    image: postgres:18
    volumes:
      - ./db-backups:/backups
    env_file:
      - .env
    entrypoint: >
      bash -c "pg_dump -h db -p 5432 -U ${POSTGRES_USER:-postgres} -Fc
      -d ${POSTGRES_DB:-psycho_db}
      -f /backups/backup-$(date +%Y%m%d_%H%M%S).dump"
    networks:
      - psycho-db-network
  media-backup:
    image: ubuntu:latest
    volumes:
      - media:/mediafiles:ro
      - ./media-backups:/backups
    entrypoint: >
      bash -c "tar czf /backups/media-$(date +%Y%m%d_%H%M%S).tar.gz /mediafiles"

# --------------------------------------------

volumes:
  db-data:
    driver: local
  static:
    driver: local
  media:
    driver: local

networks:
  psycho-front-network:
  psycho-back-network:
  psycho-db-network:

