services:
  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # The env file should set POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./postgres-init
        target: /docker-entrypoint-initdb.d
        read_only: true
      - db-data:/var/lib/postgresql/data
    networks:
      - psycho-backend-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 0s

  back:
    image: kadolphe/psycho-back-tests:latest
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - psycho-backend-network
    ports:
      - "8000:8000"
    healthcheck:
      test: curl -f http://localhost:8000/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db-data:
    driver: local

networks:
  psycho-backend-network:
    driver: bridge

