services:
  db:
    image: postgres:18
    container_name: psycho-db
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # The env file should set POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./postgres-init
        target: /docker-entrypoint-initdb.d
        read_only: true
      - db-data:/var/lib/postgresql
    networks:
      - psycho-db-network
    # For admin tasks outside the container
    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 0s

  redis:
    image: redis:8.2
    container_name: psycho-redis
    restart: always
    networks:
      - psycho-back-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  # We will be using two instances of the backend for load balancing.
  back-1:
    image: kadolphe/psycho-back-tests:latest
    container_name: psycho-back-1
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
    - ALLOWED_HOSTS=localhost,127.0.0.1,psycho-tests.defense.bj,psycho-tests.emaa.mil.bj
    - CORS_ALLOWED_ORIGINS=http://psycho-tests.defense.bj,https://psycho-tests.defense.bj,http://localhost,http://psycho-tests.emaa.mil.bj,https://psycho-tests.emaa.mil.bj
    networks:
      - psycho-back-network
      - psycho-db-network
    healthcheck:
      test: python -c 'import urllib.request; urllib.request.urlopen("http://localhost:8000")' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - static:/staticfiles
      - media:/media

  back-2:
      image: kadolphe/psycho-back-tests:latest
      container_name: psycho-back-2
      restart: always
      depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy
      env_file:
        - .env
      environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,psycho-tests.defense.bj,psycho-tests.emaa.mil.bj
      - CORS_ALLOWED_ORIGINS=http://psycho-tests.defense.bj,https://psycho-tests.defense.bj,http://localhost,http://psycho-tests.emaa.mil.bj,https://psycho-tests.emaa.mil.bj
      networks:
        - psycho-back-network
        - psycho-db-network
      healthcheck:
        test: python -c 'import urllib.request; urllib.request.urlopen("http://localhost:8000")' || exit 1
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
      volumes:
        - static:/staticfiles
        - media:/media

  front:
    image: kadolphe/psycho-front-tests:latest
    container_name: psycho-front
    restart: always
    depends_on:
      back-1:
        condition: service_healthy
      back-2:
        condition: service_healthy
    networks:
      - psycho-front-network
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # reverse proxy and load balancing
  nginx:
    image: nginx:1.29
    container_name: psycho-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/staticfiles:ro
      - media:/media:ro
    depends_on:
      back-1:
        condition: service_healthy
      back-2:
        condition: service_healthy
      front:
        condition: service_healthy
    networks:
      - psycho-back-network
      - psycho-front-network
    ports:
      - "81:80"

volumes:
  db-data:
    driver: local
  static:
    driver: local
  media:
    driver: local

networks:
  psycho-front-network:
  psycho-back-network:
  psycho-db-network:
      

