worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    sendfile on;

    # Upstream of backend servers (for load balancing if needed)
    upstream backend {
        server back-1:8000;
        server back-2:8000;
    }

    upstream frontend {
        server front:80;
    }

    # Include all server blocks from conf.d
    include /etc/nginx/conf.d/*.conf;
}
