# Generated by Django 5.2.7 on 2025-10-21 07:41

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import psycho.models
import psycho.utils.models_utils
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompositionCentre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Centre de composition",
                        max_length=99,
                        unique=True,
                        verbose_name="Composition centre",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=199, verbose_name="The centre location"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Composition Centres",
            },
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Intitulé du diplôme, e.g., Bachelor of Science in Computer Science",
                        max_length=99,
                        verbose_name="The degree name",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("Highschool", "High School"),
                            ("Bachelor", "Bachelor"),
                            ("Master", "Master"),
                            ("Phd", "Phd"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="The degree type",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        max_length=99,
                        verbose_name="The institution that awarded the degree",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Degrees",
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=99, verbose_name="The university name"),
                ),
            ],
            options={
                "verbose_name_plural": "Universities",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address of the user",
                        max_length=100,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "blank": "Username cannot be empty.",
                            "unique": "This username is already taken.",
                        },
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=(models.Model, psycho.utils.models_utils.NormalizeFieldsMixin),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "admin_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the admin",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Admin's first name",
                        max_length=100,
                        verbose_name="admin first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Admin's last name",
                        max_length=100,
                        verbose_name="admin last name",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "blank": "An email address is required.",
                            "unique": "This email address is already taken.",
                        },
                        help_text="Admin's email address",
                        max_length=100,
                        unique=True,
                        verbose_name="admin email",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Admin's phone number",
                        max_length=128,
                        region="BJ",
                        unique=True,
                        verbose_name="Admin phone number",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date at which the admin creates its profile",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date at which the admin updates its profile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(models.Model, psycho.utils.models_utils.NormalizeFieldsMixin),
        ),
        migrations.CreateModel(
            name="ApplicantProfile",
            fields=[
                (
                    "applicant_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the applicant",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "npi",
                    models.CharField(
                        db_index=True,
                        help_text="Personal identification number (NPI).",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "NPI must contain only digits."
                            ),
                            django.core.validators.MinLengthValidator(
                                10, "NPI must be exactly 10 digits."
                            ),
                            django.core.validators.MaxLengthValidator(
                                10, "NPI must be exactly 10 digits."
                            ),
                        ],
                        verbose_name="Personal identification number (NPI)",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        error_messages={"blank": "First name cannot be empty."},
                        help_text="Applicant's first name",
                        max_length=100,
                        verbose_name="Applicant first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        error_messages={"blank": "Last name cannot be empty."},
                        help_text="Applicant's last name",
                        max_length=100,
                        verbose_name="Applicant last name",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        error_messages={"blank": "Date of birth is required."},
                        help_text="Applicant's date of birth",
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        error_messages={"blank": "Place of birth is required."},
                        help_text="Applicant's place of birth",
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        help_text="Applicant gender",
                        max_length=1,
                    ),
                ),
                (
                    "wears_glasses",
                    models.BooleanField(
                        error_messages={
                            "invalid": "Please specify if the applicant wears glasses."
                        },
                        help_text="Does the applicant use spectacles?",
                        verbose_name="Wears glasses",
                    ),
                ),
                (
                    "personnel_type",
                    models.CharField(
                        choices=[("Civilian", "Civilian"), ("Military", "Military")],
                        help_text="Civilian or Military",
                        max_length=8,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Applicant email address",
                        max_length=100,
                        unique=True,
                        verbose_name="Applicant email",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        error_messages={"invalid": "A valid phone number is required."},
                        help_text="Applicant phone number",
                        max_length=128,
                        region="BJ",
                        unique=True,
                        verbose_name="Applicant phone number",
                    ),
                ),
                (
                    "date_registered",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date at which the applicant creates their profile",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date at which the applicant updates their profile",
                    ),
                ),
                (
                    "academic_level",
                    models.CharField(
                        choices=[
                            ("BAC", "BAC"),
                            ("BAC+1", "BAC+1"),
                            ("BAC+2", "BAC+2"),
                            ("BAC+3", "BAC+3"),
                            ("BAC+4", "BAC+4"),
                            ("BAC+5", "BAC+5"),
                        ],
                        help_text="Current academic level of the applicant",
                        max_length=6,
                        verbose_name="Applicant academic level",
                    ),
                ),
                (
                    "baccalaureate_series",
                    models.CharField(
                        choices=[
                            ("D", "BAC D"),
                            ("C", "BAC C"),
                            ("E", "BAC E"),
                            ("F", "BAC F"),
                        ],
                        help_text="Series of the baccalaureate obtained",
                        max_length=1,
                        verbose_name="Baccalaureate series",
                    ),
                ),
                (
                    "baccalaureate_average",
                    models.FloatField(
                        help_text="Average grade obtained at the baccalaureate exam",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="Average at baccalaureate exam",
                    ),
                ),
                (
                    "birth_certificate",
                    models.FileField(
                        help_text="Scanned copy of the applicant's birth certificate",
                        upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                            "birth_certificates"
                        ),
                        validators=[psycho.models.validate_uploaded_file_size],
                        verbose_name="Birth certificate",
                    ),
                ),
                (
                    "criminal_record",
                    models.FileField(
                        help_text="Recent criminal record extract for the applicant",
                        upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                            "criminal_records"
                        ),
                        validators=[psycho.models.validate_uploaded_file_size],
                        verbose_name="Criminal record",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "highest_degree",
                    models.ForeignKey(
                        help_text="Highest degree obtained by the applicant",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicants",
                        to="psycho.degree",
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicant profile",
                "verbose_name_plural": "Applicant profiles",
                "ordering": ["last_name", "first_name"],
            },
            bases=(models.Model, psycho.utils.models_utils.NormalizeFieldsMixin),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "application_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the application",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tracking_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="A human-readable reference to track the application",
                    ),
                ),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Incomplete", "Incomplete"),
                        ],
                        default="Pending",
                        help_text="Status of the application",
                        max_length=20,
                    ),
                ),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="psycho.applicantprofile",
                    ),
                ),
                (
                    "composition_centre",
                    models.ForeignKey(
                        help_text="Centre where the applicant will take the exam",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="psycho.compositioncentre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["-date_submitted"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Incomplete", "Incomplete"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Status before change",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Incomplete", "Incomplete"),
                        ],
                        max_length=20,
                        verbose_name="Status after change",
                    ),
                ),
                ("date_changed", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional comment about the change",
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="psycho.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Application status histories",
                "ordering": ["-date_changed"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalApplicantProfile",
            fields=[
                (
                    "applicant_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the applicant",
                    ),
                ),
                (
                    "npi",
                    models.CharField(
                        db_index=True,
                        help_text="Personal identification number (NPI).",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "NPI must contain only digits."
                            ),
                            django.core.validators.MinLengthValidator(
                                10, "NPI must be exactly 10 digits."
                            ),
                            django.core.validators.MaxLengthValidator(
                                10, "NPI must be exactly 10 digits."
                            ),
                        ],
                        verbose_name="Personal identification number (NPI)",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        error_messages={"blank": "First name cannot be empty."},
                        help_text="Applicant's first name",
                        max_length=100,
                        verbose_name="Applicant first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        error_messages={"blank": "Last name cannot be empty."},
                        help_text="Applicant's last name",
                        max_length=100,
                        verbose_name="Applicant last name",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        error_messages={"blank": "Date of birth is required."},
                        help_text="Applicant's date of birth",
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        error_messages={"blank": "Place of birth is required."},
                        help_text="Applicant's place of birth",
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        help_text="Applicant gender",
                        max_length=1,
                    ),
                ),
                (
                    "wears_glasses",
                    models.BooleanField(
                        error_messages={
                            "invalid": "Please specify if the applicant wears glasses."
                        },
                        help_text="Does the applicant use spectacles?",
                        verbose_name="Wears glasses",
                    ),
                ),
                (
                    "personnel_type",
                    models.CharField(
                        choices=[("Civilian", "Civilian"), ("Military", "Military")],
                        help_text="Civilian or Military",
                        max_length=8,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Applicant email address",
                        max_length=100,
                        verbose_name="Applicant email",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        error_messages={"invalid": "A valid phone number is required."},
                        help_text="Applicant phone number",
                        max_length=128,
                        region="BJ",
                        verbose_name="Applicant phone number",
                    ),
                ),
                (
                    "date_registered",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Date at which the applicant creates their profile",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Date at which the applicant updates their profile",
                    ),
                ),
                (
                    "academic_level",
                    models.CharField(
                        choices=[
                            ("BAC", "BAC"),
                            ("BAC+1", "BAC+1"),
                            ("BAC+2", "BAC+2"),
                            ("BAC+3", "BAC+3"),
                            ("BAC+4", "BAC+4"),
                            ("BAC+5", "BAC+5"),
                        ],
                        help_text="Current academic level of the applicant",
                        max_length=6,
                        verbose_name="Applicant academic level",
                    ),
                ),
                (
                    "baccalaureate_series",
                    models.CharField(
                        choices=[
                            ("D", "BAC D"),
                            ("C", "BAC C"),
                            ("E", "BAC E"),
                            ("F", "BAC F"),
                        ],
                        help_text="Series of the baccalaureate obtained",
                        max_length=1,
                        verbose_name="Baccalaureate series",
                    ),
                ),
                (
                    "baccalaureate_average",
                    models.FloatField(
                        help_text="Average grade obtained at the baccalaureate exam",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="Average at baccalaureate exam",
                    ),
                ),
                (
                    "birth_certificate",
                    models.TextField(
                        help_text="Scanned copy of the applicant's birth certificate",
                        max_length=100,
                        validators=[psycho.models.validate_uploaded_file_size],
                        verbose_name="Birth certificate",
                    ),
                ),
                (
                    "criminal_record",
                    models.TextField(
                        help_text="Recent criminal record extract for the applicant",
                        max_length=100,
                        validators=[psycho.models.validate_uploaded_file_size],
                        verbose_name="Criminal record",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "highest_degree",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Highest degree obtained by the applicant",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="psycho.degree",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Applicant profile",
                "verbose_name_plural": "historical Applicant profiles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HRManagerProfile",
            fields=[
                (
                    "manager_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the HR manager",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="HR manager's first name",
                        max_length=100,
                        verbose_name="HR manager first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="HR manager's last name",
                        max_length=100,
                        verbose_name="HR manager last name",
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "email",
                    models.EmailField(
                        help_text="HR manager's email address",
                        max_length=100,
                        unique=True,
                        verbose_name="HR manager email",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="HR manager's phone number",
                        max_length=128,
                        region="BJ",
                        unique=True,
                        verbose_name="HR manager phone number",
                    ),
                ),
                (
                    "date_registered",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date at which the HR manager creates its profile",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date at which the HR manager updates its profile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_manager_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "HR Manager",
                "ordering": ["last_name"],
                "permissions": [
                    ("can_review_applications", "Can review applications"),
                    (
                        "can_manage_applicants_profiles",
                        "Can manage applicants profiles",
                    ),
                    ("can_manage_applications", "Can manage applications"),
                ],
            },
            bases=(models.Model, psycho.utils.models_utils.NormalizeFieldsMixin),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "review_id",
                    models.AutoField(
                        editable=False,
                        help_text="Unique identifier for the review",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_reviewed", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "comments",
                    models.TextField(
                        help_text="Comments from the HR manager about the application"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="Application being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="psycho.application",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="HR manager who reviewed the application",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="psycho.hrmanagerprofile",
                        verbose_name="reviewer",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="hrmanagerprofile",
            constraint=models.UniqueConstraint(
                fields=("last_name", "date_of_birth"),
                name="manager_unique_lower_last_name_date_of_birth",
                violation_error_message="The HR manager already exists.",
            ),
        ),
    ]
