# Generated by Django 5.2 on 2025-05-04 16:42

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the admin', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Admin's first name", max_length=100, verbose_name='admin first name')),
                ('last_name', models.CharField(help_text="Admin's last name", max_length=100, verbose_name='admin last name')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(help_text="Admin's email address", max_length=100, unique=True, verbose_name='admin email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text="Admin's phone number", max_length=128, region='BJ', unique=True, verbose_name='Admin phone number')),
                ('date_registered', models.DateTimeField(auto_now_add=True, help_text='Date at which the admin creates its profile')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date at which the admin updates its profile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the application', primary_key=True, serialize=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Incomplete', 'Incomplete')], default='Pending', help_text='Status of the application', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HRManager',
            fields=[
                ('manager_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the HR manager', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="HR manager's first name", max_length=100, verbose_name='HR manager first name')),
                ('last_name', models.CharField(help_text="HR manager's last name", max_length=100, verbose_name='HR manager last name')),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(help_text="HR manager's email address", max_length=100, unique=True, verbose_name='HR manager email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text="HR manager's phone number", max_length=128, region='BJ', unique=True, verbose_name='HR manager phone number')),
                ('date_registered', models.DateTimeField(auto_now_add=True, help_text='Date at which the HR manager creates its profile')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date at which the HR manager updates its profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(editable=False, help_text='Unique identifier for the review', primary_key=True, serialize=False)),
                ('date_reviewed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(help_text='Comments from the HR manager about the application')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='applicant',
            name='unique_lower_last_name_date_of_birth_email',
        ),
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(fields=('last_name', 'date_of_birth'), name='unique_lower_last_name_date_of_birth', violation_error_message='The applicant already exists.'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='psycho.applicant'),
        ),
        migrations.AddField(
            model_name='hrmanager',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='application',
            field=models.ForeignKey(help_text='Application being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='psycho.application'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(help_text='HR manager who reviewed the application', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='psycho.hrmanager', verbose_name='reviewer'),
        ),
    ]
