# Generated by Django 5.2.7 on 2025-10-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psycho", "0002_seed_composition_centres"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompositionCentre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Centre de composition",
                        max_length=99,
                        unique=True,
                        verbose_name="Composition centre",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=199, verbose_name="The centre location"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Composition Centres",
            },
        ),
        migrations.AlterModelOptions(
            name="applicantprofile",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Applicant profile",
                "verbose_name_plural": "Applicant profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="application",
            options={
                "ordering": ["-date_submitted"],
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
        migrations.AlterField(
            model_name="application",
            name="tracking_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="A human-readable reference to track the application",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="composition_centre",
            field=models.ForeignKey(
                default="Cotonou",
                help_text="Centre where the applicant will take the exam",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="psycho.compositioncentre",
            ),
            preserve_default=False,
        ),
    ]
