# Generated by Django 5.2.7 on 2025-10-27 16:31

import psycho.models
import psycho.utils.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psycho", "0002_seed_composition_centres"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantprofile",
            name="baccalaureate_certificate",
            field=models.FileField(
                default="NULL",
                help_text="Scanned copy of the applicant's baccalaureate certificate",
                upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                    "baccalaureate_certificates"
                ),
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Baccalaureate certificate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="highest_degree_certificate",
            field=models.FileField(
                blank=True,
                help_text="Scanned copy of the applicant's highest degree certificate",
                null=True,
                upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                    "highest_degree_certificates"
                ),
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Highest degree certificate",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplicantprofile",
            name="baccalaureate_certificate",
            field=models.TextField(
                default="NULL",
                help_text="Scanned copy of the applicant's baccalaureate certificate",
                max_length=100,
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Baccalaureate certificate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalapplicantprofile",
            name="highest_degree_certificate",
            field=models.TextField(
                blank=True,
                help_text="Scanned copy of the applicant's highest degree certificate",
                max_length=100,
                null=True,
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Highest degree certificate",
            ),
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="criminal_record",
            field=models.FileField(
                blank=True,
                help_text="Recent criminal record extract for the applicant",
                null=True,
                upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                    "criminal_records"
                ),
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Criminal record",
            ),
        ),
        migrations.AlterField(
            model_name="compositioncentre",
            name="name",
            field=models.CharField(
                db_index=True,
                error_messages={
                    "unique": "A composition centre with this name already exists."
                },
                help_text="Centre de composition",
                max_length=99,
                unique=True,
                verbose_name="Composition centre",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplicantprofile",
            name="criminal_record",
            field=models.TextField(
                blank=True,
                help_text="Recent criminal record extract for the applicant",
                max_length=100,
                null=True,
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Criminal record",
            ),
        ),
    ]
