# Generated by Django 5.2 on 2025-05-04 17:10

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho', '0002_admin_application_hrmanager_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('applicant_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the applicant', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="ApplicantProfile's first name", max_length=100, verbose_name='applicant first name')),
                ('last_name', models.CharField(help_text="ApplicantProfile's last name", max_length=100, verbose_name='applicant last name')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(db_index=True, help_text="ApplicantProfile's email address", max_length=100, unique=True, verbose_name='applicant email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text="ApplicantProfile's phone number", max_length=128, region='BJ', unique=True, verbose_name='ApplicantProfile phone number')),
                ('date_registered', models.DateTimeField(auto_now_add=True, help_text='Date at which the applicant creates its profile')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date at which the applicant updates its profile')),
            ],
            options={
                'ordering': ['date_registered'],
            },
        ),
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminProfile',
        ),
        migrations.RenameModel(
            old_name='HRManager',
            new_name='HRManagerProfile',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='hrmanagerprofile',
            options={'ordering': ['last_name'], 'verbose_name': 'HR Manager'},
        ),
        migrations.AddConstraint(
            model_name='hrmanagerprofile',
            constraint=models.UniqueConstraint(fields=('last_name', 'date_of_birth'), name='manager_unique_lower_last_name_date_of_birth', violation_error_message='The HR manager already exists.'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='psycho.applicantprofile'),
        ),
        migrations.AddConstraint(
            model_name='applicantprofile',
            constraint=models.UniqueConstraint(fields=('last_name', 'date_of_birth'), name='applicant_unique_lower_last_name_date_of_birth', violation_error_message='The applicant already exists.'),
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
