# Generated by Django 5.2 on 2025-05-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psycho', '0003_applicantprofile_rename_admin_adminprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['date_submitted'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='hrmanagerprofile',
            options={'ordering': ['last_name'], 'permissions': [('can_review_applications', 'Can review applications'), ('can_manage_applicants_profiles', 'Can manage applicants profiles'), ('can_manage_applications', 'Can manage applications')], 'verbose_name': 'HR Manager'},
        ),
    ]
