# Generated by Django 5.2.7 on 2025-10-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psycho", "0003_applicantprofile_baccalaureate_certificate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hrmanagerprofile",
            options={
                "ordering": ["last_name"],
                "permissions": [
                    (
                        "can_manage_applicants_profiles",
                        "Can manage applicants profiles",
                    ),
                    ("can_manage_applications", "Can manage applications"),
                ],
                "verbose_name": "HR Manager",
            },
        ),
        migrations.RemoveConstraint(
            model_name="hrmanagerprofile",
            name="manager_unique_lower_last_name_date_of_birth",
        ),
        migrations.RemoveField(
            model_name="hrmanagerprofile",
            name="date_of_birth",
        ),
    ]
