# Generated by Django 5.2 on 2025-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho', '0004_alter_application_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='date_registered',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(error_messages={'blank': 'An email address is required.', 'unique': 'This email address is already taken.'}, help_text="Admin's email address", max_length=100, unique=True, verbose_name='admin email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email address of the user', max_length=100, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username cannot be empty.', 'unique': 'This username is already taken.'}, max_length=150, unique=True),
        ),
    ]
