# Generated by Django 5.2.7 on 2025-11-05 10:09

import django.db.models.deletion
import psycho.models
import psycho.utils.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psycho", "0004_alter_hrmanagerprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantprofile",
            name="identity_document",
            field=models.FileField(
                default="NULL",
                help_text="Scanned copy of the applicant's identity document (obligatoire)",
                upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                    "identity_documents"
                ),
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Pièce d'identité",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="medical_certificate",
            field=models.FileField(
                blank=True,
                help_text="Medical fitness certificate (optionnel)",
                null=True,
                upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                    "medical_certificates"
                ),
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Certificat d'aptitude médical",
            ),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="nationality_certificate",
            field=models.FileField(
                blank=True,
                help_text="Certificate of nationality (optionnel)",
                null=True,
                upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                    "nationality_certificates"
                ),
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Certificat de nationalité",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplicantprofile",
            name="identity_document",
            field=models.TextField(
                default="NULL",
                help_text="Scanned copy of the applicant's identity document (obligatoire)",
                max_length=100,
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Pièce d'identité",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalapplicantprofile",
            name="medical_certificate",
            field=models.TextField(
                blank=True,
                help_text="Medical fitness certificate (optionnel)",
                max_length=100,
                null=True,
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Certificat d'aptitude médical",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplicantprofile",
            name="nationality_certificate",
            field=models.TextField(
                blank=True,
                help_text="Certificate of nationality (optionnel)",
                max_length=100,
                null=True,
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Certificat de nationalité",
            ),
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="baccalaureate_certificate",
            field=models.FileField(
                help_text="Scanned copy of the applicant's baccalaureate certificate",
                upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                    "baccalaureate_certificates"
                ),
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Attestation du Bac",
            ),
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="birth_certificate",
            field=models.FileField(
                help_text="Scanned copy of the applicant's birth certificate",
                upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                    "birth_certificates"
                ),
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Acte de naissance",
            ),
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="criminal_record",
            field=models.FileField(
                blank=True,
                help_text="Recent criminal record extract for the applicant",
                null=True,
                upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                    "criminal_records"
                ),
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Casier judiciaire",
            ),
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="highest_degree_certificate",
            field=models.FileField(
                blank=True,
                help_text="Scanned copy of the applicant's highest degree certificate",
                null=True,
                upload_to=psycho.utils.models_utils.ApplicantUploadTo(
                    "highest_degree_certificates"
                ),
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Diplôme élevé",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="applicant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application",
                to="psycho.applicantprofile",
                verbose_name="Candidat",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="composition_centre",
            field=models.ForeignKey(
                help_text="Centre where the applicant will take the exam",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="psycho.compositioncentre",
                verbose_name="Centre",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="date_submitted",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Soumis le"),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Incomplete", "Incomplete"),
                ],
                default="Pending",
                help_text="Status of the application",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tracking_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A human-readable reference to track the application",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Numéro de suivi",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplicantprofile",
            name="baccalaureate_certificate",
            field=models.TextField(
                help_text="Scanned copy of the applicant's baccalaureate certificate",
                max_length=100,
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Attestation du Bac",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplicantprofile",
            name="birth_certificate",
            field=models.TextField(
                help_text="Scanned copy of the applicant's birth certificate",
                max_length=100,
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Acte de naissance",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplicantprofile",
            name="criminal_record",
            field=models.TextField(
                blank=True,
                help_text="Recent criminal record extract for the applicant",
                max_length=100,
                null=True,
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Casier judiciaire",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplicantprofile",
            name="highest_degree_certificate",
            field=models.TextField(
                blank=True,
                help_text="Scanned copy of the applicant's highest degree certificate",
                max_length=100,
                null=True,
                validators=[psycho.models.validate_uploaded_file_size],
                verbose_name="Diplôme élevé",
            ),
        ),
    ]
