# Generated by Django 5.2 on 2025-06-29 18:02

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psycho', '0005_rename_date_registered_adminprofile_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text="ApplicantProfile's phone number", max_length=128, region='BJ', unique=True, verbose_name='Applicant phone number'),
        ),
    ]
