# Generated by Django 5.2.4 on 2025-08-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho', '0006_alter_applicantprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default=0, max_length=14, verbose_name='A human-readable reference to track the application'),
            preserve_default=False,
        ),
    ]
