# Generated by Django 5.2.4 on 2025-08-06 13:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho', '0007_application_tracking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name='The university name')),
            ],
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='baccalaureate_average',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='Average at baccalaureate exam'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='baccalaureate_series',
            field=models.CharField(choices=[('D', 'BAC D'), ('C', 'BAC C'), ('E', 'BAC E'), ('F', 'BAC F')], default='BAC D', max_length=2, verbose_name='The type of baccalaureate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='degree',
            field=models.CharField(choices=[('HIGHSCHOOL', 'High School'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master')], default='High School', verbose_name='The applicant highest study degree'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='university_average',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='Average for the university degree'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='university_field_of_study',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='The degree specialization'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Graduate', to='psycho.university'),
        ),
    ]
