# Generated by Django 5.2.4 on 2025-08-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psycho", "0008_university_applicantprofile_baccalaureate_average_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantprofile",
            name="baccalaureate_session",
            field=models.DateField(
                default="2012-07-01", verbose_name="Baccalaureate session"
            ),
            preserve_default=False,
        ),
    ]
