# Generated by Django 5.2.4 on 2025-08-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psycho", "0009_applicantprofile_baccalaureate_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantprofile",
            name="university_field_of_study",
            field=models.CharField(
                blank=True, max_length=99, null=True, verbose_name="Study field"
            ),
        ),
    ]
