# Generated by Django 5.2.4 on 2025-08-07 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psycho", "0010_alter_applicantprofile_university_field_of_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantprofile",
            name="baccalaureate_average",
            field=models.FloatField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(20.0),
                ],
                verbose_name="Average at baccalaureate exam",
            ),
            preserve_default=False,
        ),
    ]
