# Generated by Django 5.2.6 on 2025-09-09 09:13

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psycho", "0011_alter_applicantprofile_baccalaureate_average"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicantprofile",
            options={"ordering": ["-date_registered"]},
        ),
        migrations.AlterModelOptions(
            name="university",
            options={"verbose_name_plural": "Universities"},
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="degree",
            field=models.CharField(
                choices=[
                    ("HIGHSCHOOL", "High School"),
                    ("BACHELOR", "Bachelor"),
                    ("MASTER", "Master"),
                    ("PHD", "Phd"),
                ],
                max_length=20,
                verbose_name="The applicant highest study degree",
            ),
        ),
        migrations.AlterField(
            model_name="applicantprofile",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graduates",
                to="psycho.university",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tracking_id",
            field=models.CharField(
                max_length=14,
                unique=True,
                verbose_name="A human-readable reference to track the application",
            ),
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Incomplete", "Incomplete"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Status before change",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Incomplete", "Incomplete"),
                        ],
                        max_length=20,
                        verbose_name="Status after change",
                    ),
                ),
                ("date_changed", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Optional comment about the change"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="psycho.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_changed"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalApplicantProfile",
            fields=[
                (
                    "applicant_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the applicant",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="ApplicantProfile's first name",
                        max_length=100,
                        verbose_name="applicant first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="ApplicantProfile's last name",
                        max_length=100,
                        verbose_name="applicant last name",
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="ApplicantProfile's email address",
                        max_length=100,
                        verbose_name="applicant email",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        help_text="ApplicantProfile's phone number",
                        max_length=128,
                        region="BJ",
                        verbose_name="Applicant phone number",
                    ),
                ),
                (
                    "date_registered",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Date at which the applicant creates its profile",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Date at which the applicant updates its profile",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("HIGHSCHOOL", "High School"),
                            ("BACHELOR", "Bachelor"),
                            ("MASTER", "Master"),
                            ("PHD", "Phd"),
                        ],
                        max_length=20,
                        verbose_name="The applicant highest study degree",
                    ),
                ),
                (
                    "baccalaureate_series",
                    models.CharField(
                        choices=[
                            ("D", "BAC D"),
                            ("C", "BAC C"),
                            ("E", "BAC E"),
                            ("F", "BAC F"),
                        ],
                        max_length=2,
                        verbose_name="The type of baccalaureate",
                    ),
                ),
                (
                    "baccalaureate_average",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="Average at baccalaureate exam",
                    ),
                ),
                (
                    "baccalaureate_session",
                    models.DateField(verbose_name="Baccalaureate session"),
                ),
                (
                    "university_field_of_study",
                    models.CharField(
                        blank=True, max_length=99, null=True, verbose_name="Study field"
                    ),
                ),
                (
                    "university_average",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="Average for the university degree",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="psycho.university",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical applicant profile",
                "verbose_name_plural": "historical applicant profiles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
