# Generated by Django 5.2.6 on 2025-09-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psycho", "0012_alter_applicantprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationstatushistory",
            options={
                "ordering": ["-date_changed"],
                "verbose_name_plural": "Application status histories",
            },
        ),
        migrations.AlterField(
            model_name="application",
            name="tracking_id",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                unique=True,
                verbose_name="A human-readable reference to track the application",
            ),
        ),
    ]
