# Generated by Django 5.2.6 on 2025-09-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psycho", "0013_alter_applicationstatushistory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationstatushistory",
            name="note",
            field=models.TextField(
                blank=True, help_text="Optional comment about the change", null=True
            ),
        ),
    ]
